version: '3.1'

services:
  app: 
    image: node-starter
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - app-db
    volumes:
      - /app/node_modules
      - .:/app

  app-db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: blablabla
    ports:
      - 5432:5432
    # volumes:
    #   - start_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

# volumes:
#   start_data:
